# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 719bc55997220b4be32f9ebaaa1b4952ccd9012588a7e97b8b7bc9cdfc854fdbee157a5b33c8b4f69869b64a57df2eafbb791573a9bdf3d2faee320f98600cfa
  mailer_host: localhost:3000
  mailer_address: smtp.gmail.com
  mailer_port: 587
  mailer_user_name: nokuk.dev@gmail.com
  mailer_password: 2Oh_awhtJCvYGFAIsGkd4w
  mailer_domain: sapsb.com
  aws_access_key_id: AKIAIMPWJXZ4VS5WYIFQ
  aws_secret_access_key: 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
  fog_directory: sapsb-dev
  sendgrid_api_key: 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

test:
  secret_key_base: 240e706ed5f86094e67137ecab71958274aa9305ce2803042e519b064e2824982fd4a1aeab9c7cfa96c3858055f2349b12f5abd24279b3a0b42e64a5c8d35bec
  mailer_host: localhost:3000
  mailer_address: smtp.gmail.com
  mailer_port: 587
  mailer_user_name: nokuk.dev@gmail.com
  aws_access_key_id: AKIAIMPWJXZ4VS5WYIFQ
  aws_secret_access_key: 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
  mailer_password: 2Oh_awhtJCvYGFAIsGkd4w
  mailer_domain: sapsb.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  sentry_key: <%= ENV["SENTRY_KEY"] %>
  sentry_secret: <%= ENV["SENTRY_SECRET"] %>
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  fog_directory: <%= ENV["FOG_DIRECTORY"] %>
  sentry_key: <%= ENV["SENTRY_KEY"] %>
  sentry_secret: <%= ENV["SENTRY_SECRET"] %>
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>
